### ISSUE TITLE
how to access the paper [1]

### ISSUE THREAD

**Issue by lixiaoyu0575** [fernandoandreotti/cinc-challenge2017#1]
Is the paper available on the internet ? ("Comparing Feature Based Classifiers and Convolutional Neural Networks to Detect Arrhythmia from Short Segments of ECG")

**Comment by fernandoandreotti** [comment]
Dear Xiaoyu, usually the CinC conference pre-prints and IEEE proceedings are released around december-january. I have emailed you the preprint for the time being.

**Comment by hellopipu** [comment]
Hi , the paper is still not available on the internet , could you please email the preprint to me ? Thanks a lot!

**Comment by fernandoandreotti** [comment]
Sorry for that, the conference is being slow with this.

**Comment by fernandoandreotti** [comment]
Challenge paper pre-prints are finally available under: https://physionet.org/challenge/2017/papers/
