### ISSUE TITLE
HRbpm

### ISSUE THREAD

**Issue by imanalikhani** [fernandoandreotti/cinc-challenge2017#11]
Hi 
Thanks for amazing toolbox you prepared.
HRbpm in in ExtractFeatures should be HR in bpm I assume?!
Since in the code :
HRbpm = median(60./(diff(qrsseg{end})));
The sampling frequency is missing!?

**Comment by fernandoandreotti** [comment]
Yes, thank you for noticing it. It got lost with the last modifications. I have corrected the line to be:
` HRbpm = median(60./(diff(qrsseg{end}./fs)));`
