### ISSUE TITLE
get_hrv small problem

### ISSUE THREAD

**Issue by imanalikhani** [fernandoandreotti/cinc-challenge2017#12]
Hi Fernando
there is a problem in get_hrv function 
HRV.NN50=sum(D>0.05); line 119
you have done the calculation in ms, so this should be abs(D)>50 I guess.
Iman

**Comment by fernandoandreotti** [comment]
Hi, you were right again. @oliver-carr has fixed that just now, see 2407ac43c771403e9ee75af404329d250619b2c0

**Comment by imanalikhani** [comment]
@oliver-carr  and @fernandoandreotti  why not abs(D)>50!?
because I guess 50 ms **difference** between two beats matter for NN50.

**Comment by oliver-carr** [comment]
@imanalikhani thank you for finding this error. I have corrected the mistake, it is now changed to:

HRV.NN50=sum(abs(D)>50);
