### ISSUE TITLE
maxpooling at x1

### ISSUE THREAD

**Issue by iman2011** [fernandoandreotti/cinc-challenge2017#13]
Hi,
In the second convolutional block you have in train_model.py line 208: 
x1 = MaxPooling1D(pool_size=poolsize, strides=poolstr)(x1) and then the maxpooling for shortcut path.
But in the paper Rajpurkar et al. this maxpooling is not part of the architecture. (according to Fig 2. of their paper). 
Would you please let me know how would it affect the training?!
Iman

**Comment by fernandoandreotti** [comment]
Hi Iman,

You refer to the first residual block on Fig. 2. The shortcut connection has a maxpool, therefore on the left column you also should perform it so that the tensors dimensions agree. Also, on the paper there is this sentence:

> When  a  residual block subsamples the input, the corresponding shortcut connections also subsample their input using a Max Pooling operation with the same subsample factor.

Best, Fernando
