### ISSUE TITLE
Hello,can I run the deeplearn-approach code without docker?

### ISSUE THREAD

**Issue by githubhahaha** [fernandoandreotti/cinc-challenge2017#14]
I know docker is very convenient, but my server was a **docker**. I found docker can't run in a docker, so I want to know if I don't use docker what requirements should I prepare or code I must change.

Thanks!

**Comment by fernandoandreotti** [comment]
Hi, have a look at the `Dockerfile` for the requirements needed to run this code: https://github.com/fernandoandreotti/cinc-challenge2017/blob/master/deeplearn-approach/docker/Dockerfile.cpu

**Comment by githubhahaha** [comment]
Thanks!

Just now I read the three `.py` file and something confused me. In my project, I want to train a new model, so first I should use the `cincset_files2matrix.py` to generate a `trainingset.mat` then use `train_model.py` to train a model and test the accuracy, is that right? Of course I should overwrite those parameters with mine.
As a green hand, I even don't know how to get started :(

**Comment by fernandoandreotti** [comment]
Exactly, feel free to post any specific issues you encounter here.

**Comment by githubhahaha** [comment]
You are a generous person, thanks
