### ISSUE TITLE
Error loading model

### ISSUE THREAD

**Issue by king-no-crown** [fernandoandreotti/cinc-challenge2017#15]
When I use your model to predict the data, I make the following error:
Error in loading the saved optimizer '
                              'state. As a result, your model is '
                              'starting with a freshly initialized '
                              'optimizer.
How to solve it？
In addition, download a good training set, how to use your train.py for training

**Comment by fernandoandreotti** [comment]
Sorry for the long delay. Can you please specify the steps you've taken to reproduce the error?

**Comment by king-no-crown** [comment]
Sorry, I have solved the problem so far.The question I am facing now is what types of heart disease are represented by A, N, O and ~. Is there any detailed introduction?

**Comment by king-no-crown** [comment]
In addition, what is the final accuracy rate of the parameters you set?

**Comment by fernandoandreotti** [comment]
Hi, this was our contribution to the Physionet Challenge 2017 (https://physionet.org/content/challenge-2017/1.0.0/). The dataset as well as test scores are available in this website.

**Comment by king-no-crown** [comment]
I found a problem when I was training the model:
Cvconfusion [:, :, counter] = confusion_matrix (ytrue ypred)
ValueError: could not broadcast input array from shape (3,3) into shape (4,4)
Confusion_matrix is 3x3, how do you make it 4x4?

**Comment by fernandoandreotti** [comment]
@king-no-crown it looks like the one of the classes was not present on either ytrue or ypred. You can try:
`confusion_matrix (ytrue ypred, labels=range(3))`
