### ISSUE TITLE
About the testdata.

### ISSUE THREAD

**Issue by dalvlv** [fernandoandreotti/cinc-challenge2017#2]
Can you provide a testdata to estimate performance of the algorithm ? And can you also email me the preprint of this paper? Thanks a lot.

**Comment by fernandoandreotti** [comment]
Dear Haoqi,

Data was provided by the CinC Challenge and is available at https://physionet.org/challenge/2017/ .

I've just sent you the pre-print for the challenge paper.

Best, Fernando
