### ISSUE TITLE
total number of features

### ISSUE THREAD

**Issue by vinayakumarr** [fernandoandreotti/cinc-challenge2017#6]
in readme you told the total number of features is 169. But when i run the extractfeatures.m file, i am getting 174 features.

**Comment by fernandoandreotti** [comment]
Dear Kumarr,

Thank you for pointing this out. I have indeed wrongly added two features to the function which I intended to remove. Your table should be Nx171, being `N` the number of segments, the first two columns the recording (`rec_number`) and segment number (`seg_number`). Therefore the total of features should be 169. For more information see commit f4dbaa3d395e077ecef52c0710a511720e9afd1b
