### ISSUE TITLE
Unable to train the net in matlab

### ISSUE THREAD

**Issue by aravindkota** [fernandoandreotti/cinc-challenge2017#7]
Hi I'm getting an error while running TrainClassifier.m during the step of crossvalidation loop 1,
the following is the error message.
"
NaN's cannot be converted to logicals.

Error in nntraining.fix_nan_inputs>iCopyNaN (line 134)
    t{i}(isnan(yi)) = NaN;

Error in nntraining.fix_nan_inputs (line 57)
        T = iCopyNaN(Y,T);

Error in nntraining.setup>setupPerWorker (line 104)
[X,Xi,Ai,T] = nntraining.fix_nan_inputs(net,X,Xi,Ai,T,Q,TS);

Error in nntraining.setup (line 43)
  [net,data,tr,err] = setupPerWorker(net,trainFcn,X,Xi,Ai,T,EW,enableConfigure);

Error in network/train (line 335)
[net,data,tr,err] = nntraining.setup(net,net.trainFcn,X,Xi,Ai,T,EW,enableConfigure,isComposite);

Error in TrainClassifier (line 123)
    net = train(net,In(trainidx,:)',Outbi(trainidx,:)');
"

**Comment by fernandoandreotti** [comment]
Hi, from the error log it is clear that you have NaNs on your data. Have a check on the features before you attempt to train a classifier.

**Comment by aravindkota** [comment]
there is a nan to numeric converter command in the function, i have checked the features file before the training set, didn't find any NaN values.

**Comment by fernandoandreotti** [comment]
Have you checked the labels as well? Maybe the Nans are there.
